version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
    - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 730054542356.dkr.ecr.ap-northeast-1.amazonaws.com
    - REPO=`aws ecr describe-repositories --repository-names example --output text --query "repositories[0].repositoryUri"`
    - IMAGE=$REPO:latest
  build:
    commands:
    - docker build -t 730054542356.dkr.ecr.ap-northeast-1.amazonaws.com/example:latest .
    - docker push 730054542356.dkr.ecr.ap-northeast-1.amazonaws.com/example:latest
  post_build:
    commands:
    - printf '[{"name":"example","imageUri":"%s"}]' 730054542356.dkr.ecr.ap-northeast-1.amazonaws.com/example:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json